### ISSUE TITLE
build failed in android 

### ISSUE THREAD

**Issue by MalinPramoditha** [react-native-kit/react-native-track-player#653]
build failed after installing track player in react-native 0.60.0. ,works with react-native 0.59.0,

here is the error
/Users/conconsolutions1/Documents/projects/rhythmfm/node_modules/react-native-track-player/android/src/main/java/com/guichaguri/trackplayer/service/MusicService.java:11: error: cannot find symbol
import android.support.v4.app.NotificationCompat;
                             ^
  symbol:   class NotificationCompat
  location: package android.support.v4.app
/Users/conconsolutions1/Documents/projects/rhythmfm/node_modules/react-native-track-player/android/src/main/java/com/guichaguri/trackplayer/service/MusicService.java:12: error: package android.support.v4.content does not exist
import android.support.v4.content.LocalBroadcastManager;
                                 ^
/Users/conconsolutions1/Documents/projects/rhythmfm/node_modules/react-native-track-player/android/src/main/java/com/guichaguri/trackplayer/service/MusicService.java:13: error: cannot find symbol
import android.support.v4.media.session.MediaButtonReceiver;
                                       ^
  symbol:   class MediaButtonReceiver
  location: package android.support.v4.media.session
/Users/conconsolutions1/Documents/projects/rhythmfm/node_modules/react-native-track-player/android/src/main/java/com/guichaguri/trackplayer/service/MusicManager.java:19: error: package android.support.annotation does not exist
import android.support.annotation.RequiresApi;
                                 ^
/Users/conconsolutions1/Documents/projects/rhythmfm/node_modules/react-native-track-player/android/src/main/java/com/guichaguri/trackplayer/service/metadata/MetadataManager.java:12: error: cannot find symbol
import android.support.v4.app.NotificationCompat;
                             ^
  symbol:   class NotificationCompat
  location: package android.support.v4.app
/Users/conconsolutions1/Documents/projects/rhythmfm/node_modules/react-native-track-player/android/src/main/java/com/guichaguri/trackplayer/service/metadata/MetadataManager.java:13: error: package android.support.v4.app.NotificationCompat does not exist
import android.support.v4.app.NotificationCompat.Action;
                                                ^
/Users/conconsolutions1/Documents/projects/rhythmfm/node_modules/react-native-track-player/android/src/main/java/com/guichaguri/trackplayer/service/metadata/MetadataManager.java:16: error: package android.support.v4.media.app.NotificationCompat does not exist
import android.support.v4.media.app.NotificationCompat.MediaStyle;
                                                      ^
/Users/conconsolutions1/Documents/projects/rhythmfm/node_modules/react-native-track-player/android/src/main/java/com/guichaguri/trackplayer/service/metadata/MetadataManager.java:17: error: cannot find symbol
import android.support.v4.media.session.MediaButtonReceiver;
                                       ^
  symbol:   class MediaButtonReceiver
  location: package android.support.v4.media.session
/Users/conconsolutions1/Documents/projects/rhythmfm/node_modules/react-native-track-player/android/src/main/java/com/guichaguri/trackplayer/service/metadata/MetadataManager.java:48: error: package NotificationCompat does not exist
    private NotificationCompat.Builder builder;
                              ^
/Users/conconsolutions1/Documents/projects/rhythmfm/node_modules/react-native-track-player/android/src/main/java/com/guichaguri/trackplayer/service/metadata/MetadataManager.java:50: error: cannot find symbol
    private Action previousAction, rewindAction, playAction, pauseAction, stopAction, forwardAction, nextAction;
            ^
  symbol:   class Action
  location: class MetadataManager
/Users/conconsolutions1/Documents/projects/rhythmfm/node_modules/react-native-track-player/android/src/main/java/com/guichaguri/trackplayer/service/metadata/MetadataManager.java:322: error: cannot find symbol
    private Action createAction(List<Integer> caps, long action, String title, int icon) {
            ^
  symbol:   class Action
  location: class MetadataManager
/Users/conconsolutions1/Documents/projects/rhythmfm/node_modules/react-native-track-player/android/src/main/java/com/guichaguri/trackplayer/service/metadata/MetadataManager.java:328: error: cannot find symbol
    private void addAction(Action action, long id, List<Integer> compact) {
                           ^
  symbol:   class Action
  location: class MetadataManager
/Users/conconsolutions1/Documents/projects/rhythmfm/node_modules/react-native-track-player/android/src/main/java/com/guichaguri/trackplayer/service/MusicManager.java:49: error: cannot find symbol
    @RequiresApi(26)
     ^
  symbol:   class RequiresApi
  location: class MusicManager
/Users/conconsolutions1/Documents/projects/rhythmfm/node_modules/react-native-track-player/android/src/main/java/com/guichaguri/trackplayer/module/MusicModule.java:49: error: cannot find symbol
        LocalBroadcastManager manager = LocalBroadcastManager.getInstance(context);
        ^
  symbol:   class LocalBroadcastManager
  location: class MusicModule
/Users/conconsolutions1/Documents/projects/rhythmfm/node_modules/react-native-track-player/android/src/main/java/com/guichaguri/trackplayer/module/MusicModule.java:49: error: cannot find symbol
        LocalBroadcastManager manager = LocalBroadcastManager.getInstance(context);
                                        ^
  symbol:   variable LocalBroadcastManager
  location: class MusicModule
/Users/conconsolutions1/Documents/projects/rhythmfm/node_modules/react-native-track-player/android/src/main/java/com/guichaguri/trackplayer/module/MusicModule.java:60: error: cannot find symbol
            LocalBroadcastManager manager = LocalBroadcastManager.getInstance(context);
            ^
  symbol:   class LocalBroadcastManager
  location: class MusicModule
/Users/conconsolutions1/Documents/projects/rhythmfm/node_modules/react-native-track-player/android/src/main/java/com/guichaguri/trackplayer/module/MusicModule.java:60: error: cannot find symbol
            LocalBroadcastManager manager = LocalBroadcastManager.getInstance(context);
                                            ^
  symbol:   variable LocalBroadcastManager
  location: class MusicModule
/Users/conconsolutions1/Documents/projects/rhythmfm/node_modules/react-native-track-player/android/src/main/java/com/guichaguri/trackplayer/service/MusicService.java:48: error: cannot find symbol
        LocalBroadcastManager.getInstance(this).sendBroadcast(intent);
        ^
  symbol:   variable LocalBroadcastManager
  location: class MusicService
/Users/conconsolutions1/Documents/projects/rhythmfm/node_modules/react-native-track-player/android/src/main/java/com/guichaguri/trackplayer/service/MusicService.java:84: error: package NotificationCompat does not exist
                startForeground(1, new NotificationCompat.Builder(this, channel).build());
                                                         ^
/Users/conconsolutions1/Documents/projects/rhythmfm/node_modules/react-native-track-player/android/src/main/java/com/guichaguri/trackplayer/service/MusicService.java:108: error: cannot find symbol
                MediaButtonReceiver.handleIntent(manager.getMetadata().getSession(), intent);
                ^
  symbol:   variable MediaButtonReceiver
  location: class MusicService
/Users/conconsolutions1/Documents/projects/rhythmfm/node_modules/react-native-track-player/android/src/main/java/com/guichaguri/trackplayer/service/metadata/MetadataManager.java:65: error: package NotificationCompat does not exist
        this.builder = new NotificationCompat.Builder(service, Utils.NOTIFICATION_CHANNEL);
                                             ^
/Users/conconsolutions1/Documents/projects/rhythmfm/node_modules/react-native-track-player/android/src/main/java/com/guichaguri/trackplayer/service/metadata/MetadataManager.java:86: error: cannot find symbol
        builder.setCategory(NotificationCompat.CATEGORY_TRANSPORT);
                            ^
  symbol:   variable NotificationCompat
  location: class MetadataManager
/Users/conconsolutions1/Documents/projects/rhythmfm/node_modules/react-native-track-player/android/src/main/java/com/guichaguri/trackplayer/service/metadata/MetadataManager.java:89: error: cannot find symbol
        builder.setDeleteIntent(MediaButtonReceiver.buildMediaButtonPendingIntent(service, PlaybackStateCompat.ACTION_STOP));
                                ^
  symbol:   variable MediaButtonReceiver
  location: class MetadataManager
/Users/conconsolutions1/Documents/projects/rhythmfm/node_modules/react-native-track-player/android/src/main/java/com/guichaguri/trackplayer/service/metadata/MetadataManager.java:92: error: cannot find symbol
        builder.setVisibility(NotificationCompat.VISIBILITY_PUBLIC);
                              ^
  symbol:   variable NotificationCompat
  location: class MetadataManager
/Users/conconsolutions1/Documents/projects/rhythmfm/node_modules/react-native-track-player/android/src/main/java/com/guichaguri/trackplayer/service/metadata/MetadataManager.java:142: error: cannot find symbol
        builder.setColor(options.getInt("color", NotificationCompat.COLOR_DEFAULT));
                                                 ^
  symbol:   variable NotificationCompat
  location: class MetadataManager
/Users/conconsolutions1/Documents/projects/rhythmfm/node_modules/react-native-track-player/android/src/main/java/com/guichaguri/trackplayer/service/metadata/MetadataManager.java:251: error: cannot find symbol
            MediaStyle style = new MediaStyle();
            ^
  symbol:   class MediaStyle
  location: class MetadataManager
/Users/conconsolutions1/Documents/projects/rhythmfm/node_modules/react-native-track-player/android/src/main/java/com/guichaguri/trackplayer/service/metadata/MetadataManager.java:251: error: cannot find symbol
            MediaStyle style = new MediaStyle();
                                   ^
  symbol:   class MediaStyle
  location: class MetadataManager
/Users/conconsolutions1/Documents/projects/rhythmfm/node_modules/react-native-track-player/android/src/main/java/com/guichaguri/trackplayer/service/metadata/MetadataManager.java:258: error: cannot find symbol
                style.setCancelButtonIntent(MediaButtonReceiver.buildMediaButtonPendingIntent(service,
                                            ^
  symbol:   variable MediaButtonReceiver
  location: class MetadataManager
/Users/conconsolutions1/Documents/projects/rhythmfm/node_modules/react-native-track-player/android/src/main/java/com/guichaguri/trackplayer/service/metadata/MetadataManager.java:325: error: cannot find symbol
        return new Action(icon, title, MediaButtonReceiver.buildMediaButtonPendingIntent(service, action));
                   ^
  symbol:   class Action
  location: class MetadataManager
/Users/conconsolutions1/Documents/projects/rhythmfm/node_modules/react-native-track-player/android/src/main/java/com/guichaguri/trackplayer/service/metadata/MetadataManager.java:325: error: cannot find symbol
        return new Action(icon, title, MediaButtonReceiver.buildMediaButtonPendingIntent(service, action));
                                       ^
  symbol:   variable MediaButtonReceiver
  location: class MetadataManager
Note: /Users/conconsolutions1/Documents/projects/rhythmfm/node_modules/react-native-track-player/android/src/main/java/com/guichaguri/trackplayer/service/MusicManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
31 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-track-player:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by Guichaguri** [comment]
You should be using the version 1.2.0 for RN 0.60 and up.

**Comment by rochapablo** [comment]
On Android, `BUILD SUCCESSFUL` but I'm getting:

```
> Task :react-native-track-player:compileDebugJavaWithJavac
Note: node_modules/react-native-track-player/android/src/main/java/com/guichaguri/trackplayer/service/MusicManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
```

```
"react": "16.8.6",
"react-native": "0.60.3",
"react-native-track-player": "^1.1.8",
```

**Comment by Guichaguri** [comment]
That's a warning, it won't affect your build.
