### ISSUE TITLE
Track.setupPlayer crashes the app

### ISSUE THREAD

**Issue by mckuok** [react-native-kit/react-native-track-player#100]
Please let me know if I am using the library correctly.
I initializes the `Track.setupPlayer` at the same time as I export my main appm, but it crashes my app. 
Testing environment is Android 7.0, Moto G4.
Here are my dependencies:
```
  "dependencies": {
    "prop-types": "^15.6.0",
    "react": "16.0.0-beta.5",
    "react-native": "^0.49.5",
    "react-native-maps": "^0.19.0",
    "react-native-slider": "^0.11.0",
    "react-native-track-player": "^0.2.2",
    "react-navigation": "^1.0.0-beta.19"
  } 
```
Code:
```
import App from './app/containers/NativeStoriesApp';
import TrackPlayer from 'react-native-track-player';

export default App

TrackPlayer.setupPlayer().then(async () => {

    // Adds a track to the queue
    await TrackPlayer.add({
        id: 'trackId',
        url: 'https://nativestories.com/haloa.mp3',
        title: 'Track Title',
        artist: 'Track Artist',
    });

    // Starts playing it
    TrackPlayer.play();

});
```
Some log which I don't know if it is relevant or not:
```
12-24 04:37:23.840  6464  6464 I art     : Rejecting re-init on previously-failed class java.lang.Class<guichaguri.trackplayer.player.players.ExoPlayback>: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/exoplayer2/ExoPlayer$EventListener;
12-24 04:37:23.840  6464  6464 I art     :   at void guichaguri.trackplayer.logic.services.PlayerService.onCreate() (PlayerService.java:66)
12-24 04:37:23.840  6464  6464 I art     :   at void android.app.ActivityThread.handleCreateService(android.app.ActivityThread$CreateServiceData) (ActivityThread.java:3183)
12-24 04:37:23.840  6464  6464 I art     :   at void android.app.ActivityThread.-wrap5(android.app.ActivityThread, android.app.ActivityThread$CreateServiceData) (ActivityThread.java:-1)
12-24 04:37:23.840  6464  6464 I art     :   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1563)
12-24 04:37:23.840  6464  6464 I art     :   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
12-24 04:37:23.840  6464  6464 I art     :   at void android.os.Looper.loop() (Looper.java:154)
12-24 04:37:23.840  6464  6464 I art     :   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6123)
12-24 04:37:23.840  6464  6464 I art     :   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
12-24 04:37:23.840  6464  6464 I art     :   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:867)
12-24 04:37:23.840  6464  6464 I art     :   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:757)
12-24 04:37:23.840  6464  6464 I art     : Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.exoplayer2.ExoPlayer$EventListener" on path: DexPathList[[zip file "/data/app/com.nativestoriesmobile-2/base.apk"],nativeLibraryDirectories=[/data/app/com.nativestoriesmobile-2/lib/arm, /system/fake-libs, /data/app/com.nativestoriesmobile-2/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
12-24 04:37:23.840  6464  6464 I art     :   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
12-24 04:37:23.840  6464  6464 I art     :   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380)
12-24 04:37:23.840  6464  6464 I art     :   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
12-24 04:37:23.840  6464  6464 I art     :   at void guichaguri.trackplayer.logic.services.PlayerService.onCreate() (PlayerService.java:66)
12-24 04:37:23.840  6464  6464 I art     :   at void android.app.ActivityThread.handleCreateService(android.app.ActivityThread$CreateServiceData) (ActivityThread.java:3183)
12-24 04:37:23.840  6464  6464 I art     :   at void android.app.ActivityThread.-wrap5(android.app.ActivityThread, android.app.ActivityThread$CreateServiceData) (ActivityThread.java:-1)
12-24 04:37:23.840  6464  6464 I art     :   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1563)
12-24 04:37:23.840  6464  6464 I art     :   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
12-24 04:37:23.840  6464  6464 I art     :   at void android.os.Looper.loop() (Looper.java:154)
12-24 04:37:23.840  6464  6464 I art     :   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6123)
12-24 04:37:23.840  6464  6464 I art     :   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
12-24 04:37:23.840  6464  6464 I art     :   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:867)
12-24 04:37:23.841  6464  6464 I art     :   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:757)
12-24 04:37:23.841  6464  6464 I art     : 
12-24 04:37:23.862  6464  6464 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.cast.framework.CastOptions>: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/internal/safeparcel/AbstractSafeParcelable;
12-24 04:37:23.862  6464  6464 I art     :   at com.google.android.gms.cast.framework.CastContext com.google.android.gms.cast.framework.CastContext.getSharedInstance(android.content.Context) ((null):-1)
12-24 04:37:23.862  6464  6464 I art     :   at guichaguri.trackplayer.cast.GoogleCast guichaguri.trackplayer.cast.GoogleCast.initialize(android.content.Context, guichaguri.trackplayer.logic.MediaManager) (GoogleCast.java:25)
12-24 04:37:23.862  6464  6464 I art     :   at void guichaguri.trackplayer.logic.MediaManager.<init>(guichaguri.trackplayer.logic.services.PlayerService) (MediaManager.java:45)
12-24 04:37:23.862  6464  6464 I art     :   at void guichaguri.trackplayer.logic.services.PlayerService.onCreate() (PlayerService.java:66)
12-24 04:37:23.862  6464  6464 I art     :   at void android.app.ActivityThread.handleCreateService(android.app.ActivityThread$CreateServiceData) (ActivityThread.java:3183)
12-24 04:37:23.862  6464  6464 I art     :   at void android.app.ActivityThread.-wrap5(android.app.ActivityThread, android.app.ActivityThread$CreateServiceData) (ActivityThread.java:-1)
12-24 04:37:23.862  6464  6464 I art     :   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1563)
12-24 04:37:23.862  6464  6464 I art     :   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
12-24 04:37:23.862  6464  6464 I art     :   at void android.os.Looper.loop() (Looper.java:154)
12-24 04:37:23.862  6464  6464 I art     :   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6123)
12-24 04:37:23.862  6464  6464 I art     :   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
12-24 04:37:23.862  6464  6464 I art     :   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:867)
12-24 04:37:23.862  6464  6464 I art     :   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:757)
12-24 04:37:23.862  6464  6464 I art     : Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.internal.safeparcel.AbstractSafeParcelable" on path: DexPathList[[zip file "/data/app/com.nativestoriesmobile-2/base.apk"],nativeLibraryDirectories=[/data/app/com.nativestoriesmobile-2/lib/arm, /system/fake-libs, /data/app/com.nativestoriesmobile-2/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
12-24 04:37:23.862  6464  6464 I art     :   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
12-24 04:37:23.862  6464  6464 I art     :   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380)
12-24 04:37:23.862  6464  6464 I art     :   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
12-24 04:37:23.862  6464  6464 I art     :   at com.google.android.gms.cast.framework.CastContext com.google.android.gms.cast.framework.CastContext.getSharedInstance(android.content.Context) ((null):-1)
12-24 04:37:23.862  6464  6464 I art     :   at guichaguri.trackplayer.cast.GoogleCast guichaguri.trackplayer.cast.GoogleCast.initialize(android.content.Context, guichaguri.trackplayer.logic.MediaManager) (GoogleCast.java:25)
12-24 04:37:23.862  6464  6464 I art     :   at void guichaguri.trackplayer.logic.MediaManager.<init>(guichaguri.trackplayer.logic.services.PlayerService) (MediaManager.java:45)
12-24 04:37:23.862  6464  6464 I art     :   at void guichaguri.trackplayer.logic.services.PlayerService.onCreate() (PlayerService.java:66)
12-24 04:37:23.862  6464  6464 I art     :   at void android.app.ActivityThread.handleCreateService(android.app.ActivityThread$CreateServiceData) (ActivityThread.java:3183)
12-24 04:37:23.862  6464  6464 I art     :   at void android.app.ActivityThread.-wrap5(android.app.ActivityThread, android.app.ActivityThread$CreateServiceData) (ActivityThread.java:-1)
12-24 04:37:23.862  6464  6464 I art     :   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1563)
12-24 04:37:23.862  6464  6464 I art     :   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
12-24 04:37:23.862  6464  6464 I art     :   at void android.os.Looper.loop() (Looper.java:154)
12-24 04:37:23.862  6464  6464 I art     :   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6123)
12-24 04:37:23.862  6464  6464 I art     :   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
12-24 04:37:23.862  6464  6464 I art     :   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:867)
12-24 04:37:23.862  6464  6464 I art     :   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:757)
12-24 04:37:23.862  6464  6464 I art     : 
12-24 04:37:23.863  6464  6464 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.cast.framework.CastOptions>: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/internal/safeparcel/AbstractSafeParcelable;
12-24 04:37:23.863  6464  6464 I art     :   at com.google.android.gms.cast.framework.CastContext com.google.android.gms.cast.framework.CastContext.getSharedInstance(android.content.Context) ((null):-1)
12-24 04:37:23.863  6464  6464 I art     :   at guichaguri.trackplayer.cast.GoogleCast guichaguri.trackplayer.cast.GoogleCast.initialize(android.content.Context, guichaguri.trackplayer.logic.MediaManager) (GoogleCast.java:25)
12-24 04:37:23.863  6464  6464 I art     :   at void guichaguri.trackplayer.logic.MediaManager.<init>(guichaguri.trackplayer.logic.services.PlayerService) (MediaManager.java:45)
12-24 04:37:23.863  6464  6464 I art     :   at void guichaguri.trackplayer.logic.services.PlayerService.onCreate() (PlayerService.java:66)
12-24 04:37:23.863  6464  6464 I art     :   at void android.app.ActivityThread.handleCreateService(android.app.ActivityThread$CreateServiceData) (ActivityThread.java:3183)
12-24 04:37:23.863  6464  6464 I art     :   at void android.app.ActivityThread.-wrap5(android.app.ActivityThread, android.app.ActivityThread$CreateServiceData) (ActivityThread.java:-1)
12-24 04:37:23.863  6464  6464 I art     :   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1563)
12-24 04:37:23.863  6464  6464 I art     :   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
12-24 04:37:23.863  6464  6464 I art     :   at void android.os.Looper.loop() (Looper.java:154)
12-24 04:37:23.863  6464  6464 I art     :   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6123)
12-24 04:37:23.863  6464  6464 I art     :   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
12-24 04:37:23.863  6464  6464 I art     :   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:867)
12-24 04:37:23.863  6464  6464 I art     :   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:757)
12-24 04:37:23.863  6464  6464 I art     : Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.internal.safeparcel.AbstractSafeParcelable" on path: DexPathList[[zip file "/data/app/com.nativestoriesmobile-2/base.apk"],nativeLibraryDirectories=[/data/app/com.nativestoriesmobile-2/lib/arm, /system/fake-libs, /data/app/com.nativestoriesmobile-2/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
12-24 04:37:23.863  6464  6464 I art     :   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
12-24 04:37:23.863  6464  6464 I art     :   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380)
12-24 04:37:23.863  6464  6464 I art     :   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
12-24 04:37:23.863  6464  6464 I art     :   at com.google.android.gms.cast.framework.CastContext com.google.android.gms.cast.framework.CastContext.getSharedInstance(android.content.Context) ((null):-1)
12-24 04:37:23.863  6464  6464 I art     :   at guichaguri.trackplayer.cast.GoogleCast guichaguri.trackplayer.cast.GoogleCast.initialize(android.content.Context, guichaguri.trackplayer.logic.MediaManager) (GoogleCast.java:25)
12-24 04:37:23.863  6464  6464 I art     :   at void guichaguri.trackplayer.logic.MediaManager.<init>(guichaguri.trackplayer.logic.services.PlayerService) (MediaManager.java:45)
12-24 04:37:23.863  6464  6464 I art     :   at void guichaguri.trackplayer.logic.services.PlayerService.onCreate() (PlayerService.java:66)
12-24 04:37:23.863  6464  6464 I art     :   at void android.app.ActivityThread.handleCreateService(android.app.ActivityThread$CreateServiceData) (ActivityThread.java:3183)
12-24 04:37:23.863  6464  6464 I art     :   at void android.app.ActivityThread.-wrap5(android.app.ActivityThread, android.app.ActivityThread$CreateServiceData) (ActivityThread.java:-1)
12-24 04:37:23.863  6464  6464 I art     :   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1563)
12-24 04:37:23.863  6464  6464 I art     :   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
12-24 04:37:23.863  6464  6464 I art     :   at void android.os.Looper.loop() (Looper.java:154)
12-24 04:37:23.864  6464  6464 I art     :   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6123)
12-24 04:37:23.864  6464  6464 I art     :   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
12-24 04:37:23.864  6464  6464 I art     :   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:867)
12-24 04:37:23.864  6464  6464 I art     :   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:757)
12-24 04:37:23.864  6464  6464 I art     : 
12-24 04:37:23.868  6464  6464 D AndroidRuntime: Shutting down VM
12-24 04:37:23.869  6464  6464 E AndroidRuntime: FATAL EXCEPTION: main
12-24 04:37:23.869  6464  6464 E AndroidRuntime: Process: com.nativestoriesmobile, PID: 6464
12-24 04:37:23.869  6464  6464 E AndroidRuntime: java.lang.NoSuchMethodError: No static method zzh(Ljava/lang/String;Ljava/lang/Object;)Ljava/lang/String; in class Lcom/google/android/gms/common/internal/zzab; or its super classes (declaration of 'com.google.android.gms.common.internal.zzab' appears in /data/app/com.nativestoriesmobile-2/base.apk)
12-24 04:37:23.869  6464  6464 E AndroidRuntime: 	at com.google.android.gms.cast.internal.zzm.<init>(Unknown Source)
12-24 04:37:23.869  6464  6464 E AndroidRuntime: 	at com.google.android.gms.cast.internal.zzm.<init>(Unknown Source)
12-24 04:37:23.869  6464  6464 E AndroidRuntime: 	at com.google.android.gms.cast.framework.CastContext.<clinit>(Unknown Source)
12-24 04:37:23.869  6464  6464 E AndroidRuntime: 	at com.google.android.gms.cast.framework.CastContext.getSharedInstance(Unknown Source)
12-24 04:37:23.869  6464  6464 E AndroidRuntime: 	at guichaguri.trackplayer.cast.GoogleCast.initialize(GoogleCast.java:25)
12-24 04:37:23.869  6464  6464 E AndroidRuntime: 	at guichaguri.trackplayer.logic.MediaManager.<init>(MediaManager.java:45)
12-24 04:37:23.869  6464  6464 E AndroidRuntime: 	at guichaguri.trackplayer.logic.services.PlayerService.onCreate(PlayerService.java:66)
12-24 04:37:23.869  6464  6464 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3183)
12-24 04:37:23.869  6464  6464 E AndroidRuntime: 	at android.app.ActivityThread.-wrap5(ActivityThread.java)
12-24 04:37:23.869  6464  6464 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1563)
12-24 04:37:23.869  6464  6464 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
12-24 04:37:23.869  6464  6464 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
12-24 04:37:23.869  6464  6464 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6123)
12-24 04:37:23.869  6464  6464 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-24 04:37:23.869  6464  6464 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
12-24 04:37:23.869  6464  6464 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
12-24 04:37:23.871  1476 19717 W ActivityManager:   Force finishing activity com.nativestoriesmobile/.MainActivity
12-24 04:37:23.874  1476  6555 W DropBoxManagerService: Dropping: data_app_crash (1591 > 0 bytes)
12-24 04:37:23.879   554   719 I SFPerfTracer:      triggers: (rate: 23:646) (993369 sw vsyncs) (0 skipped) (636:2029435 vsyncs) (638:3238306)
12-24 04:37:23.890  1476  3665 E ActivityManager: Sending non-protected broadcast com.motorola.motocare.INTENT_TRIGGER from system 3914:com.motorola.process.system/1000 pkg com.motorola.motgeofencesvc
12-24 04:37:23.890  1476  3665 E ActivityManager: java.lang.Throwable
12-24 04:37:23.890  1476  3665 E ActivityManager: 	at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:18226)
12-24 04:37:23.890  1476  3665 E ActivityManager: 	at com.android.server.am.ActivityManagerService.broadcastIntent(ActivityManagerService.java:18826)
12-24 04:37:23.890  1476  3665 E ActivityManager: 	at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:512)
12-24 04:37:23.890  1476  3665 E ActivityManager: 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2906)
12-24 04:37:23.890  1476  3665 E ActivityManager: 	at android.os.Binder.execTransact(Binder.java:565)
12-24 04:37:23.950  1476 22524 I OpenGLRenderer: Initialized EGL, version 1.4
12-24 04:37:23.950  1476 22524 D OpenGLRenderer: Swap behavior 1
12-24 04:37:24.384  1476  1506 W ActivityManager: Activity pause timeout for ActivityRecord{b1a31cc u0 com.nativestoriesmobile/.MainActivity t9903 f}
12-24 04:37:24.522  1476  3993 E ActivityManager: Sending non-protected broadcast com.motorola.motocare.INTENT_TRIGGER from system 3914:com.motorola.process.system/1000 pkg com.motorola.motgeofencesvc
12-24 04:37:24.522  1476  3993 E ActivityManager: java.lang.Throwable
12-24 04:37:24.522  1476  3993 E ActivityManager: 	at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:18226)
12-24 04:37:24.522  1476  3993 E ActivityManager: 	at com.android.server.am.ActivityManagerService.broadcastIntent(ActivityManagerService.java:18826)
12-24 04:37:24.522  1476  3993 E ActivityManager: 	at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:512)
12-24 04:37:24.522  1476  3993 E ActivityManager: 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2906)
12-24 04:37:24.522  1476  3993 E ActivityManager: 	at android.os.Binder.execTransact(Binder.java:565)

```

**Comment by mckuok** [comment]
If you can set up an simple bare-bone example usage react-native project repo using this library, that would be great!

**Comment by Guichaguri** [comment]
That's a problem with the Cast SDK. Due to React Native using an older build version, it has to use an older support library, and because of that, we have to use an older Cast SDK. Turns out it has a lot of problems that have been fixed in newer versions.

We are splitting the cast support into an addon module, I'm looking into ways to fix that issue in the addon module.

The cast support has been already removed in the dev branch, you can use it for now.

**Comment by mnlbox** [comment]
I have same problem. App crash on android 5.0.1 but works on android 6 and higher.

**Comment by Guichaguri** [comment]
Use the dev branch, it should fix it

**Comment by mnlbox** [comment]
@Guichaguri How we switch to dev branch from NPM?

**Comment by Guichaguri** [comment]
@mnlbox `npm install react-native-kit/react-native-track-player#dev`

**Comment by mnlbox** [comment]
@Guichaguri when you want update npm package in npm official repository?

**Comment by Guichaguri** [comment]
When we are done recoding the cast integration to [react-native-track-casting](https://github.com/react-native-kit/react-native-track-casting)

**Comment by ianataffinity** [comment]
@mnlbox how does `npm install react-native-kit/react-native-track-player#dev` look like in the package.json file? 

I am trying to build on our test bed with the dev branch but the package.json file wont install anything than the latest version...

**Comment by mnlbox** [comment]
@Guichaguri it's still not working on android 5.0.1 (Huawei P8 Lite)
when we use TrackPlayer in a page and navigate to that page app closed without any error. (I also check log-android output many times)
Have you any plan to fix it? :disappointed:

**Comment by mnlbox** [comment]
@Guichaguri Let's continue this bug on new issue: #157

**Comment by kyungjoongo** [comment]
same issue..
react-native-track-player\android\src\main\java\guichaguri\trackplayer\metadata\components\MediaNotification.java:4: error: cannot find symbol
import android.app.NotificationChannel;

**Comment by kyungjoongo** [comment]
X:\current_real_project\track_example-player\example\node_modules\react-native-track-player\android\src\main\java\guichaguri\trackplayer\metadata\components\MediaNotification.java:4: error: cannot find symbol
import android.app.NotificationChannel;
                  ^
  symbol:   class NotificationChannel
  location: package android.app
X:\current_real_project\track_example-player\example\node_modules\react-native-track-player\android\src\main\java\guichaguri\trackplayer\metadata\components\MediaNotification.java:20: error: package android.support.v4.media.app.NotificationCompat does not exist
import android.support.v4.media.app.NotificationCompat.MediaStyle;
                                                      ^
X:\current_real_project\track_example-player\example\node_modules\react-native-track-player\android\src\main\java\guichaguri\trackplayer\metadata\components\MediaNotification.java:42: error: cannot find symbol
    private MediaStyle style;
            ^
  symbol:   class MediaStyle
  location: class MediaNotification
X:\current_real_project\track_example-player\example\node_modules\react-native-track-player\android\src\main\java\guichaguri\trackplayer\metadata\components\MediaNotification.java:82: error: cannot find symbol
    @RequiresApi(VERSION_CODES.O)
                              ^
  symbol:   variable O
  location: class VERSION_CODES
X:\current_real_project\track_example-player\example\node_modules\react-native-track-player\android\src\main\java\guichaguri\trackplayer\metadata\components\MediaNotification.java:56: error: cannot find symbol
        if(VERSION.SDK_INT >= VERSION_CODES.O) createChannel();
                                           ^
  symbol:   variable O
  location: class VERSION_CODES
X:\current_real_project\track_example-player\example\node_modules\react-native-track-player\android\src\main\java\guichaguri\trackplayer\metadata\components\MediaNotification.java:58: error: constructor Builder in class Builder cannot be applied to given types;
        this.nb = new Builder(context, "trackplayer");
                  ^
  required: Context
  found: Context,String
  reason: actual and formal argument lists differ in length
X:\current_real_project\track_example-player\example\node_modules\react-native-track-player\android\src\main\java\guichaguri\trackplayer\metadata\components\MediaNotification.java:59: error: cannot find symbol
        this.style = new MediaStyle().setMediaSession(session.getSessionToken());
                         ^
  symbol:   class MediaStyle
  location: class MediaNotification
X:\current_real_project\track_example-player\example\node_modules\react-native-track-player\android\src\main\java\guichaguri\trackplayer\metadata\components\MediaNotification.java:86: error: cannot find symbol
        NotificationChannel channel = new NotificationChannel("trackplayer", "Media controls", NotificationManager.IMPORTANCE_LOW);
        ^
  symbol:   class NotificationChannel
  location: class MediaNotification
X:\current_real_project\track_example-player\example\node_modules\react-native-track-player\android\src\main\java\guichaguri\trackplayer\metadata\components\MediaNotification.java:86: error: cannot find symbol
        NotificationChannel channel = new NotificationChannel("trackplayer", "Media controls", NotificationManager.IMPORTANCE_LOW);
                                          ^
  symbol:   class NotificationChannel
  location: class MediaNotification
X:\current_real_project\track_example-player\example\node_modules\react-native-track-player\android\src\main\java\guichaguri\trackplayer\metadata\components\MediaNotification.java:86: error: cannot find symbol
        NotificationChannel channel = new NotificationChannel("trackplayer", "Media controls", NotificationManager.IMPORTANCE_LOW);
                                                                                                                  ^
  symbol:   variable IMPORTANCE_LOW
  location: class NotificationManager
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
10 errors
:react-native-track-player:compileReleaseJavaWithJavac FAILED


FAILURE: Build failed with an exception.
BUILD FAILED

**Comment by lp4298707** [comment]
我安装了react-native-sound 之后 应用崩溃了
After I installed react-native-sound, the application crashed.

**Comment by mahmoudfelfel** [comment]
I got this error and it was fixed by adding exoplayer-core to the app level Gradle file:
```
implementation 'com.google.android.exoplayer:exoplayer-core:r2.4.3'
```
Then clean your project and build again.

**Comment by ajaykumar97** [comment]
@mahmoudfelfel did not work for me. Have you done any other modifications along with this?
